{
 "title": "Grafana Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Rpc request latency(secs)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(op_node_default_rpc_client_request_duration_seconds_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Unsafe payloads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "op_node_default_unsafe_payloads_total"
    }
   ]
  },
  {
   "title": "Sequencer resets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "op_node_default_sequencer_resets_total"
    }
   ]
  },
  {
   "title": "Rpc client requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "op_node_default_rpc_client_requests_total"
    }
   ]
  }
 ]
}